variable "environment" {}
variable "vpcblock" {}
variable "name_tag" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "Publica1block" {}
variable "Publicb1block" {}
variable "Privatea1block" {}
variable "Privatea2block" {}
variable "Privateb1block" {}
variable "Privateb2block" {}
variable "Privateb3block" {}
variable "Privateb4block" {}
